name: "Forgejo"
version: "12.0.3"
slug: "forgejo"
description: "A lightweight self-hosted Git service"
url: "https://forgejo.org/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
ports:
  "3000/tcp": 3000
  "22/tcp": 22
ports_description:
  "3000/tcp": "Forgejo Web Interface"
  "22/tcp": "Forgejo SSH Git Access"
map:
  - "3000:3000"
  - "22:22"
options:
  domain: "localhost"
  http_port: 3000
  ssh_port: 22
schema:
  domain:
    str
  http_port:
    int(1,65535)
  ssh_port:
    int(1,65535)
hassio_api: true
hassio_role: default
homeassistant_api: false
host_network: false
tmpfs: "/tmp"
